name: Setup Termux
description: Set up a Termux shell on an Android emulator

inputs:
  arch:
    description: Android emulator architecture
    required: false
    default: x86_64

runs:
  using: node24
  main: dist/index.js
  post: dist/post.js
  post-if: always()
