name: Test iOS simulator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup and Boot iOS Simulator
        uses: futureware-tech/simulator-action@v5
        with:
          os: 'iOS'
          os_version: ">=14.0"
          wait_for_boot: true

      - name: Test simulator
        run: printf "echo 'hello from the simulator'\npwd\n" | xcrun simctl spawn booted /bin/sh -s
