name: Test iOS environment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    container:
      image: 05nelsonm/build-env.ios.aarch64:latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Fetch CMake Source Code
        run: |
          uname -a
          echo "Hello"
