name: Build CMake for iOS Target

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
    CMAKE_VERSION: "4.4.3"

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Fetch CMake Source Code
        run: |
          echo "Downloading CMake Source v${CMAKE_VERSION}..."
          curl -LO https://github.com/Kitware/cmake/releases/latest/download/cmake-${CMAKE_VERSION}.tar.gz
          tar -xzf cmake-${CMAKE_VERSION}.tar.gz

      - name: Configure CMake for iOS
        run: |
          mkdir cmake-build && cd cmake-build
          
          cmake -G "Xcode" \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=OFF \
            -DCMake_BUILD_LXML=OFF \
            -DCMAKE_USE_SYSTEM_LIBRARIES=OFF \
            ../cmake-${CMAKE_VERSION}

      - name: Compile CMake for iOS
        run: |
          cd cmake-build
          cmake --build . --config Release --target cmake -- -sdk iphoneos
          cmake --build . --config Release --target ctest -- -sdk iphoneos
          cmake --build . --config Release --target cpack -- -sdk iphoneos

      - name: Verify iOS Binaries
        run: |
          ls -lh cmake-build/bin/Release-iphoneos/cmake
          file cmake-build/bin/Release-iphoneos/cmake

      - name: Upload iOS Binaries as Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: cmake-ios-binaries
          path: |
            cmake-build/bin/Release-iphoneos/cmake
            cmake-build/bin/Release-iphoneos/ctest
            cmake-build/bin/Release-iphoneos/cpack
